# Generated by Django 3.2.5 on 2021-09-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_review_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.FloatField(),
        ),
    ]
